### ISSUE TITLE
what is the ELMo?

### ISSUE THREAD

**Issue by garboa** [hpk23/SQuAD-FusionNet#1]
hello,thanks for your code in fusionNet .I note that you use the ELMo instead of CoVe ,what is the ELMo?Could you give me the paper or code for ELMo? email Garbo_Guo@163.com,thanks a lot

**Comment by hpk23** [comment]
Hi @garboa 
ELMo is contextualized word representation. 
here is the ElMo paper https://arxiv.org/abs/1802.05365

**Comment by garboa** [comment]
Thank you ,And the paper in fusionNet shows the result EM is 76, i try my best to improve the result as the paper,but failed.Do you have suggestions ?

**Comment by hpk23** [comment]
Have you ever seen that issue(https://github.com/momohuang/FusionNet-NLI/issues/1)? that will help you.
