### ISSUE TITLE
How to add the ELMO embeddings here?

### ISSUE THREAD

**Issue by LearningPytorch** [hpk23/SQuAD-FusionNet#2]
Hi,
Maybe I missed it, but how do you add the ELMO or Cove embeddings to the model? which script does that? I didn't find it in your code. Thanks

**Comment by LearningPytorch** [comment]
@hpk23 do you have any suggestions on how to add the Elmo vectors? Thank you in advance.

**Comment by hpk23** [comment]
Hi, @LearningPytorch i have updated the code to use ELMo.
If you want to use ELMo, you can set use_cove to False and use_elmo to True after installing the allennlp library.

**Comment by LearningPytorch** [comment]
Thank you very much! I'm trying this now. I will let you know if I encounter issues.
